apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-call-developer-api
  namespace: hypertheory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: on-call-developer-api
  template:
    metadata:
      labels:
        app: on-call-developer-api
    spec:
      containers:
      - name: on-call-developer-api
        image: jeffrygonzalez/oncall-api-feb-2023:v0.2
        resources:
          
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
